import { HandValue } from './hand-value';

export const suites: string[] = ['s', 'c', 'd', 'h'];

export const rankings: string[] = ['2', '3', '4', '5', '6', '7', '8', '9', 'T', 'J', 'Q', 'K', 'A'];

export const handValues: HandValue[] = [
    new HandValue('AA', 1, 1),
    new HandValue('KK', 1, 1),
    new HandValue('QQ', 1, 1),
    new HandValue('JJ', 1, 1),
    new HandValue('TT', 2, 2),
    new HandValue('99', 3, 3),
    new HandValue('88', 4, 4),
    new HandValue('77', 5, 5),
    new HandValue('66', 6, 6),
    new HandValue('55', 6, 6),
    new HandValue('44', 7, 7),
    new HandValue('33', 7, 7),
    new HandValue('22', 7, 7),

    new HandValue('AK', 1, 2),
    new HandValue('AQ', 2, 3),
    new HandValue('AJ', 2, 4),
    new HandValue('AT', 3, 6),
    new HandValue('A9', 5, 8),
    new HandValue('A8', 5, 9),
    new HandValue('A7', 5, 9),
    new HandValue('A6', 5, 9),
    new HandValue('A5', 5, 9),
    new HandValue('A4', 5, 9),
    new HandValue('A3', 5, 9),
    new HandValue('A2', 5, 9),

    new HandValue('KQ', 2, 4),
    new HandValue('KJ', 3, 5),
    new HandValue('KT', 4, 6),
    new HandValue('K9', 6, 8),
    new HandValue('K8', 7, 9),
    new HandValue('K7', 7, 9),
    new HandValue('K6', 7, 9),
    new HandValue('K5', 7, 9),
    new HandValue('K4', 7, 9),
    new HandValue('K3', 7, 9),
    new HandValue('K2', 7, 9),

    new HandValue('QJ', 3, 5),
    new HandValue('QT', 4, 6),
    new HandValue('Q9', 5, 8),
    new HandValue('Q8', 7, 9),
    new HandValue('Q7', 9, 9),
    new HandValue('Q6', 9, 9),
    new HandValue('Q5', 9, 9),
    new HandValue('Q4', 9, 9),
    new HandValue('Q3', 9, 9),
    new HandValue('Q2', 9, 9),

    new HandValue('JT', 3, 5),
    new HandValue('J9', 4, 7),
    new HandValue('J8', 6, 8),
    new HandValue('J7', 8, 9),
    new HandValue('J6', 9, 9),
    new HandValue('J5', 9, 9),
    new HandValue('J4', 9, 9),
    new HandValue('J3', 9, 9),
    new HandValue('J2', 9, 9),

    new HandValue('T9', 4, 7),
    new HandValue('T8', 5, 8),
    new HandValue('T7', 7, 9),
    new HandValue('T6', 9, 9),
    new HandValue('T5', 9, 9),
    new HandValue('T4', 9, 9),
    new HandValue('T3', 9, 9),
    new HandValue('T2', 9, 9),

    new HandValue('98', 4, 7),
    new HandValue('97', 5, 9),
    new HandValue('96', 8, 9),
    new HandValue('95', 9, 9),
    new HandValue('94', 9, 9),
    new HandValue('93', 9, 9),
    new HandValue('92', 9, 9),

    new HandValue('87', 5, 8),
    new HandValue('86', 6, 9),
    new HandValue('85', 8, 9),
    new HandValue('84', 9, 9),
    new HandValue('83', 9, 9),
    new HandValue('82', 9, 9),

    new HandValue('76', 5, 8),
    new HandValue('75', 6, 9),
    new HandValue('74', 8, 9),
    new HandValue('73', 9, 9),
    new HandValue('72', 9, 9),

    new HandValue('65', 5, 8),
    new HandValue('64', 7, 9),
    new HandValue('63', 9, 9),
    new HandValue('62', 9, 9),
    
    new HandValue('54', 6, 8),
    new HandValue('53', 7, 9),
    new HandValue('52', 9, 9),
    
    new HandValue('43', 7, 9),
    new HandValue('42', 8, 9),

    new HandValue('32', 8, 9),
];
