export const
// playedHands = [
//     'AcAd',
//     'AcAd',
//     '2C4D',
//     '2C4D',
//     '2C4D',
// ]

playedHands = [
        'AC4D',
        '8S9H',
        '4D7H',
        '6S9C',
        'JDJH',
        '5DJD',
        '6HJD',
        '3H8H',
        'TD6D',
        'AH5C',
        '4DAD',
        'AD3C',
        'AD9S',
        '2D3C',
        '9H4D',
        '3CAD',
        '5C5S',
        '4DTS',
        'JD6H',
        'QD5C',
        'TH4H',
        '4SQD',
        'JH2H',
        'KS8S',
        '8C9S',
        '7HQS',
        '8S8H',
        '6d6c',
        '3hAd',
        '5s6h',
        '3h4d',
        '2d6d',
        '7sQs',
        '5s7d',
        '7h7d',
        '7S4S',
        '8d7d',
        '4s5h',
        '2d5d',
        'Kh9d',
        '2H5s',
        '7s3d',
        '3sAh',
        'Kd3h',
        '8h9s',
        'Ac5s',
        '2h7h',
        'Th4h',
        'Jd7s',
    ]


